# Generated by Django 4.1 on 2024-09-14 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_subtitle_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
